services:
  postgres:
    ports:
      - "5435:5432"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
    env_file:
      - ../backend/.env

  frontend:
    ports:
      - "3000:3000"
