services:
  postgres:
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    env_file:
      - .env.prod
    environment:
      ENVIRONMENT: production
      CORS_ORIGINS: http://bgitu-event.ru,https://bgitu-event.ru
      DEFAULT_IMPORT_CATEGORY_ID: d25a71d1-9001-4e4c-926f-4fa2e5de013c
      UPLOAD_DIR: /app/uploads
    volumes:
      - uploads_data:/app/uploads
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"

  frontend:
    env_file:
      - .env.prod
    build:
      args:
        NEXT_PUBLIC_API_URL: http://bgitu-event.ru/api/v1

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - uploads_data:/var/www/uploads:ro

  migrate:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    entrypoint: ["alembic", "upgrade", "head"]
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:
  uploads_data:
